// import * as Types from 'mongoose;
import { Schema, model, Model, Types, Document } from 'mongoose';

// db.getCollection('banks').insertMany([
/* 1 */
export const bankinsert = [{
    _id: Types.ObjectId('5da838b11591fd466731948c'),
    loanForForeigner: false,
    loanForForeignerMarriedLocal: true,
    loanForNonCreditCardHolder: true,
    loanForCreditCardHolder: true,
    loanForNotNowCreditCardHolder: true,
    loanAlreadyExistDiffBank: true,
    loanAlreadyExistSameBank: true,
    missedLoanPaymentAllowance: true,
    abbrevation: 'RCBC',
    bankName: 'Rizal Commercial Banking Corporation',
    headquarterLocation: 'Makati',
    loanForCancelledCreditCard: false,
    propertySpecification: [
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da838b11591fd4667319491'),
            allowedPropertyType: 'APARTMENT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da838b11591fd4667319490'),
            allowedPropertyType: 'CONDOMINIUM',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da838b11591fd466731948f'),
            allowedPropertyType: 'HOUSE_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da838b11591fd466731948e'),
            allowedPropertyType: 'TOWNHOUSE',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da838b11591fd466731948d'),
            allowedPropertyType: 'VACANT_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
    ],
    interestRateDetails: {
        1: 6.38,
        2: 6.5,
        3: 6.5,
        4: 7.38,
        5: 7.38,
        6: 8.5,
        7: 8.5,
        8: 8.5,
        9: 8.5,
        10: 8.5,
        11: 10.0,
        12: 10.0,
        13: 10.0,
        14: 10.0,
        15: 10.0,
        16: 10.5,
        17: 10.5,
        18: 10.5,
        19: 10.5,
        20: 10.5,
    },
    bankFeePercent: 0.0,
    bankFeeAmount: 0.0,
    loanApplicationFeePercent: 0.0,
    loanApplicationFeeAmount: 0.0,
    loanMinAmount: 1250000.0,
    loanMaxAmount: 1000000000.0,
    minLoanDuration: 12.0,
    maxLoanDuration: 240.0,
    minAgeRequiredForLoan: 21.0,
    minMonthlyIncomeRequired: 50000.0,
    logoUrl: '/assets/banking/RCBC/RCBC Home Loans Page Logo.png',
    iconUrl: '/assets/banking/RCBC/RCBC Square Profile Photo.png',
    bannerUrl: '/assets/banking/RCBC/RCBC Profile Banner.png',
    createdAt: 1571305649165.0,
    updatedAt: 1571305649165.0,
    __v: 0.0,
},

/* 2 */
{
    _id: Types.ObjectId('5da83dd91591fd4667319499'),
    loanForForeigner: false,
    loanForForeignerMarriedLocal: true,
    loanForNonCreditCardHolder: true,
    loanForCreditCardHolder: true,
    loanForNotNowCreditCardHolder: true,
    loanAlreadyExistDiffBank: true,
    loanAlreadyExistSameBank: true,
    missedLoanPaymentAllowance: false,
    abbrevation: 'CBC',
    bankName: 'China Banking Corporation',
    headquarterLocation: 'Makati',
    loanForCancelledCreditCard: true,
    propertySpecification: [
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83dd91591fd466731949e'),
            allowedPropertyType: 'APARTMENT',
            maxLoanDurationAllowed: 10.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 35.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83dd91591fd466731949d'),
            allowedPropertyType: 'CONDOMINIUM',
            maxLoanDurationAllowed: 15.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 35.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83dd91591fd466731949c'),
            allowedPropertyType: 'HOUSE_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 35.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83dd91591fd466731949b'),
            allowedPropertyType: 'TOWNHOUSE',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 35.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83dd91591fd466731949a'),
            allowedPropertyType: 'VACANT_LOT',
            maxLoanDurationAllowed: 10.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 35.0,
        },
    ],
    interestRateDetails: {
        1: 6.0,
        2: 6.5,
        3: 6.5,
        4: 7.0,
        5: 7.0,
        6: 9.0,
        7: 9.0,
        8: 9.0,
        9: 9.0,
        10: 9.0,
        11: 6.75,
        12: 6.75,
        13: 6.75,
        14: 6.75,
        15: 6.75,
        16: 6.75,
        17: 6.75,
        18: 6.75,
        19: 6.75,
        20: 6.75,
    },
    bankFeePercent: 0.0,
    bankFeeAmount: 0.0,
    loanApplicationFeePercent: 0.0,
    loanApplicationFeeAmount: 0.0,
    loanMinAmount: 625000.0,
    loanMaxAmount: 1000000000.0,
    minLoanDuration: 12.0,
    maxLoanDuration: 240.0,
    minAgeRequiredForLoan: 21.0,
    minMonthlyIncomeRequired: 35000.0,
    logoUrl: '/assets/banking/ChinaBank/CBC Home Loans Page Logo.jpg',
    iconUrl: '/assets/banking/ChinaBank/CBC Profile Photo and Results Page Logo.jpg',
    bannerUrl: '/assets/banking/ChinaBank/CB Profile Banner 2.jpg',
    createdAt: 1571306969705.0,
    updatedAt: 1571306969705.0,
    __v: 0.0,
},

/* 3 */
{
    _id: Types.ObjectId('5da83f341591fd46673194a6'),
    loanForForeigner: false,
    loanForForeignerMarriedLocal: true,
    loanForNonCreditCardHolder: true,
    loanForCreditCardHolder: true,
    loanForNotNowCreditCardHolder: true,
    loanAlreadyExistDiffBank: true,
    loanAlreadyExistSameBank: true,
    missedLoanPaymentAllowance: false,
    abbrevation: 'BDO',
    bankName: 'Banco de Oro',
    headquarterLocation: 'Makati',
    loanForCancelledCreditCard: true,
    propertySpecification: [
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83f341591fd46673194ab'),
            allowedPropertyType: 'APARTMENT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83f341591fd46673194aa'),
            allowedPropertyType: 'CONDOMINIUM',
            maxLoanDurationAllowed: 15.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83f341591fd46673194a9'),
            allowedPropertyType: 'HOUSE_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83f341591fd46673194a8'),
            allowedPropertyType: 'TOWNHOUSE',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da83f341591fd46673194a7'),
            allowedPropertyType: 'VACANT_LOT',
            maxLoanDurationAllowed: 10.0,
            maxLoanPercent: 70.0,
            debtIncomeRatio: 40.0,
        },
    ],
    interestRateDetails: {
        1: 6.5,
        2: 7.25,
        3: 7.5,
        4: 8.0,
        5: 8.0,
        6: 6.75,
        7: 6.75,
        8: 6.75,
        9: 6.75,
        10: 6.75,
        11: 6.75,
        12: 6.75,
        13: 6.75,
        14: 6.75,
        15: 6.75,
        16: 6.75,
        17: 6.75,
        18: 6.75,
        19: 6.75,
        20: 6.75,
    },
    bankFeePercent: 0.0,
    bankFeeAmount: 0.0,
    loanApplicationFeePercent: 0.0,
    loanMinAmount: 625000.0,
    loanMaxAmount: 1000000000.0,
    minLoanDuration: 12.0,
    maxLoanDuration: 240.0,
    minAgeRequiredForLoan: 21.0,
    minMonthlyIncomeRequired: 50000.0,
    logoUrl: '/assets/banking/BDO/BDO Home Loans Page Logo.gif',
    iconUrl: '/assets/banking/BDO/BDO Square Profile Photo and Results Page Photo.jpg',
    bannerUrl: '/assets/banking/BDO/BDO Profile Page Banner.jpg',
    createdAt: 1571307316789.0,
    updatedAt: 1571307316789.0,
    __v: 0.0,
},

/* 4 */
{
    _id: Types.ObjectId('5da840c71591fd46673194b3'),
    loanForForeigner: false,
    loanForForeignerMarriedLocal: true,
    loanForNonCreditCardHolder: true,
    loanForCreditCardHolder: true,
    loanForNotNowCreditCardHolder: true,
    loanAlreadyExistDiffBank: true,
    loanAlreadyExistSameBank: true,
    missedLoanPaymentAllowance: false,
    abbrevation: 'CTBC',
    bankName: 'CTBC Bank',
    headquarterLocation: 'Taiwan',
    loanForCancelledCreditCard: true,
    propertySpecification: [
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da840c71591fd46673194b8'),
            allowedPropertyType: 'APARTMENT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da840c71591fd46673194b7'),
            allowedPropertyType: 'CONDOMINIUM',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da840c71591fd46673194b6'),
            allowedPropertyType: 'HOUSE_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da840c71591fd46673194b5'),
            allowedPropertyType: 'TOWNHOUSE',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da840c71591fd46673194b4'),
            allowedPropertyType: 'VACANT_LOT',
            maxLoanDurationAllowed: 10.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
    ],
    interestRateDetails: {
        1: 7.0,
        2: 7.65,
        3: 7.75,
        4: 8.75,
        5: 9.25,
        6: 6.75,
        7: 6.75,
        8: 6.75,
        9: 6.75,
        10: 6.75,
        11: 6.75,
        12: 6.75,
        13: 6.75,
        14: 6.75,
        15: 6.75,
        16: 6.75,
        17: 6.75,
        18: 6.75,
        19: 6.75,
        20: 6.75,
    },
    bankFeePercent: 0.0,
    bankFeeAmount: 0.0,
    loanApplicationFeePercent: 0.0,
    loanMinAmount: 625000.0,
    loanMaxAmount: 1000000000.0,
    minLoanDuration: 12.0,
    maxLoanDuration: 240.0,
    minAgeRequiredForLoan: 21.0,
    minMonthlyIncomeRequired: 50000.0,
    logoUrl: '/assets/banking/CTBC/CTBC Home Loans Page Logo.png',
    iconUrl: '/assets/banking/CTBC/CTBC Profile Photo and Results Page Logo.png',
    bannerUrl: '/assets/banking/CTBC/CTBC Profile Photo and Results Page Logo.png',
    createdAt: 1571307719705.0,
    updatedAt: 1571307719705.0,
    __v: 0.0,
},

/* 5 */
{
    _id: Types.ObjectId('5da843cfc8083d4e3e27b93a'),
    loanForForeigner: false,
    loanForForeignerMarriedLocal: true,
    loanForNonCreditCardHolder: true,
    loanForCreditCardHolder: true,
    loanForNotNowCreditCardHolder: true,
    loanAlreadyExistDiffBank: true,
    loanAlreadyExistSameBank: true,
    missedLoanPaymentAllowance: true,
    abbrevation: 'BoC',
    bankName: 'Bank of Commerce',
    headquarterLocation: 'Mandaluyoung',
    loanForCancelledCreditCard: false,
    propertySpecification: [
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da843cfc8083d4e3e27b93f'),
            allowedPropertyType: 'APARTMENT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da843cfc8083d4e3e27b93e'),
            allowedPropertyType: 'CONDOMINIUM',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da843cfc8083d4e3e27b93d'),
            allowedPropertyType: 'HOUSE_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da843cfc8083d4e3e27b93c'),
            allowedPropertyType: 'TOWNHOUSE',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da843cfc8083d4e3e27b93b'),
            allowedPropertyType: 'VACANT_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
    ],
    interestRateDetails: {
        1: 6.75,
        2: 6.75,
        3: 6.75,
        4: 6.75,
        5: 6.75,
        6: 6.75,
        7: 6.75,
        8: 6.75,
        9: 6.75,
        10: 6.75,
        11: 6.75,
        12: 6.75,
        13: 6.75,
        14: 6.75,
        15: 6.75,
        16: 6.75,
        17: 6.75,
        18: 6.75,
        19: 6.75,
        20: 6.75,
    },
    bankFeePercent: 0.0,
    bankFeeAmount: 0.0,
    loanApplicationFeePercent: 0.0,
    loanMinAmount: 625000.0,
    loanMaxAmount: 1000000000.0,
    minLoanDuration: 12.0,
    maxLoanDuration: 240.0,
    minAgeRequiredForLoan: 21.0,
    minMonthlyIncomeRequired: 25000.0,
    logoUrl: '/assets/banking/BoC/BoC Home Loans Page Logo.jpg',
    iconUrl: '/assets/banking/BoC/BoC Profile Banner.jpg',
    bannerUrl: '/assets/banking/BoC/BoC Profile Photo.jpg',
    createdAt: 1571308495949.0,
    updatedAt: 1571308495949.0,
    __v: 0.0,
},

/* 6 */
{
    _id: Types.ObjectId('5da8459ec8083d4e3e27b947'),
    loanForForeigner: false,
    loanForForeignerMarriedLocal: true,
    loanForNonCreditCardHolder: true,
    loanForCreditCardHolder: true,
    loanForNotNowCreditCardHolder: true,
    loanAlreadyExistDiffBank: true,
    loanAlreadyExistSameBank: true,
    missedLoanPaymentAllowance: true,
    abbrevation: 'SBC',
    bankName: 'Security Bank',
    headquarterLocation: 'Makati',
    loanForCancelledCreditCard: false,
    propertySpecification: [
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8459ec8083d4e3e27b94c'),
            allowedPropertyType: 'APARTMENT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8459ec8083d4e3e27b94b'),
            allowedPropertyType: 'CONDOMINIUM',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8459ec8083d4e3e27b94a'),
            allowedPropertyType: 'HOUSE_LOT',
            maxLoanDurationAllowed: 25.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8459ec8083d4e3e27b949'),
            allowedPropertyType: 'TOWNHOUSE',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8459ec8083d4e3e27b948'),
            allowedPropertyType: 'VACANT_LOT',
            maxLoanDurationAllowed: 15.0,
            maxLoanPercent: 70.0,
            debtIncomeRatio: 40.0,
        },
    ],
    interestRateDetails: {
        1: 6.75,
        2: 6.75,
        3: 6.75,
        4: 6.75,
        5: 6.75,
        6: 6.75,
        7: 6.75,
        8: 6.75,
        9: 6.75,
        10: 6.75,
        11: 6.75,
        12: 6.75,
        13: 6.75,
        14: 6.75,
        15: 6.75,
        16: 6.75,
        17: 6.75,
        18: 6.75,
        19: 6.75,
        20: 6.75,
        21: 6.75,
        22: 6.75,
        23: 6.75,
        24: 6.75,
        25: 6.75,
    },
    bankFeePercent: 0.0,
    bankFeeAmount: 0.0,
    loanApplicationFeePercent: 0.0,
    loanMinAmount: 1250000.0,
    loanMaxAmount: 1000000000.0,
    minLoanDuration: 12.0,
    maxLoanDuration: 300.0,
    minAgeRequiredForLoan: 21.0,
    minMonthlyIncomeRequired: 50000.0,
    logoUrl: '/assets/banking/Security Bank/SecB Home Loans Page Logo 2.jpg',
    iconUrl: '/assets/banking/Security Bank/SecB Profile Banner.jpg',
    bannerUrl: '/assets/banking/Security Bank/SecB Profile Picture and Results Page Logo 2jpg.jpg',
    createdAt: 1571308958467.0,
    updatedAt: 1571308958467.0,
    __v: 0.0,
},

/* 7 */
{
    _id: Types.ObjectId('5da8481dc8083d4e3e27b954'),
    loanForForeigner: false,
    loanForForeignerMarriedLocal: true,
    loanForNonCreditCardHolder: true,
    loanForCreditCardHolder: true,
    loanForNotNowCreditCardHolder: true,
    loanAlreadyExistDiffBank: true,
    loanAlreadyExistSameBank: true,
    missedLoanPaymentAllowance: true,
    abbrevation: 'AUB',
    bankName: 'Asia United Bank',
    headquarterLocation: 'Pasig City',
    loanForCancelledCreditCard: false,
    propertySpecification: [
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8481dc8083d4e3e27b959'),
            allowedPropertyType: 'APARTMENT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8481dc8083d4e3e27b958'),
            allowedPropertyType: 'CONDOMINIUM',
            maxLoanDurationAllowed: 15.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8481dc8083d4e3e27b957'),
            allowedPropertyType: 'HOUSE_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8481dc8083d4e3e27b956'),
            allowedPropertyType: 'TOWNHOUSE',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            _id: Types.ObjectId('5da8481dc8083d4e3e27b955'),
            allowedPropertyType: 'VACANT_LOT',
            maxLoanDurationAllowed: 10.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 30.0,
        },
    ],
    interestRateDetails: {
        1: 6.75,
        2: 7.0,
        3: 7.0,
        4: 7.5,
        5: 7.5,
        6: 6.75,
        7: 6.75,
        8: 6.75,
        9: 6.75,
        10: 6.75,
        11: 6.75,
        12: 6.75,
        13: 6.75,
        14: 6.75,
        15: 6.75,
        16: 6.75,
        17: 6.75,
        18: 6.75,
        19: 6.75,
        20: 6.75,
    },
    bankFeePercent: 0.0,
    bankFeeAmount: 0.0,
    loanApplicationFeePercent: 0.0,
    loanMinAmount: 1250000.0,
    loanMaxAmount: 1000000000.0,
    minLoanDuration: 12.0,
    maxLoanDuration: 240.0,
    minAgeRequiredForLoan: 21.0,
    minMonthlyIncomeRequired: 40000.0,
    logoUrl: '/assets/banking/AUB/AUB Home Loans Page Logo.jpg',
    iconUrl: '/assets/banking/AUB/AUB Profile Banner.jpg',
    bannerUrl: '/assets/banking/AUB/AUB Square Profile Photo and Results Page Photo.jpg',
    createdAt: 1571309597618.0,
    updatedAt: 1571309597618.0,
    __v: 0.0,
},
{
    _id: Types.ObjectId('5df781adff3306fb47b485b0'),
    loanForForeigner: false,
    loanForForeignerMarriedLocal: true,
    loanForNonCreditCardHolder: true,
    loanForCreditCardHolder: true,
    loanForNotNowCreditCardHolder: true,
    loanAlreadyExistDiffBank: true,
    loanAlreadyExistSameBank: true,
    missedLoanPaymentAllowance: true,
    abbrevation: 'BPI',
    bankName: 'Bank of the Philippine Islands',
    headquarterLocation: 'Makati',
    loanForCancelledCreditCard: true,
    propertySpecification: [
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            allowedPropertyType: 'APARTMENT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            allowedPropertyType: 'CONDOMINIUM',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            allowedPropertyType: 'HOUSE_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            allowedPropertyType: 'TOWNHOUSE',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
        {
            allowedPropertyStatus: [
                'FORECLOSED',
                'PRE_SELLING',
                'READY_FOR_OCCUPANCY',
                'RESELLING',
                'REFINANCING',
            ],
            allowedPropertyType: 'VACANT_LOT',
            maxLoanDurationAllowed: 20.0,
            maxLoanPercent: 80.0,
            debtIncomeRatio: 40.0,
        },
    ],
    interestRateDetails: {
        1: 5.88,
        2: 5.88,
        3: 5.88,
        4: 6.88,
        5: 6.88,
        6: 9.5,
        7: 9.5,
        8: 9.5,
        9: 9.5,
        10: 9.5,
        11: 10.5,
        12: 10.5,
        13: 10.5,
        14: 10.5,
        15: 10.5,
        16: 12.0,
        17: 12.0,
        18: 12.0,
        19: 12.0,
        20: 12.0,
    },
    bankFeePercent: 0.0,
    bankFeeAmount: 0.0,
    loanApplicationFeePercent: 0.0,
    loanMinAmount: 1250000.0,
    loanMaxAmount: 1000000000.0,
    minLoanDuration: 12.0,
    maxLoanDuration: 240.0,
    minAgeRequiredForLoan: 21.0,
    minMonthlyIncomeRequired: 50000.0,
    logoUrl: '/assets/banking/bpi-bank/logo.jpg',
    iconUrl: '/assets/banking/bpi-bank/icon.jpg',
    bannerUrl: '/assets/banking/bpi-bank/banner.jpg',
    createdAt: 1571308958467.0,
    updatedAt: 1571308958467.0,
    __v: 0.0,
}];
